import Head from "next/head";
// import Image from 'next/image'
import { useCallback, useEffect, useMemo } from "react";
import { useRouter } from "next/dist/client/router";
import { useTheme } from "../hooks/useTheme";
import useStore from "../hooks/useStore";
import shallow from "zustand/shallow";

import { queryToSections } from "../lib/serialization";
import { sectionsToImgURL } from "../lib/sectionsToImgURL";
import favicon from "../lib/favicon";
import {
  init as initSynths,
  updateInstruments,
  getInstruments,
  getNewInstrument,
} from "../lib/instruments";

const Tone = require("tone");

import Main from "../components/main";

export default function Home() {
  // TODO:
  // fix mobile performance issues
  // midi export
  // dragging
  // instruments
  // PWA https://able.bio/drenther/building-a-progressive-web-app-with-nextjs-part-i--00edasw

  const styles = useTheme(require("../styles/Home.module.sass"));

  const [paused, bpm, setBpm, sections, setSections, instrumentIDs] = useStore(
    useCallback(
      (state) => [
        state.paused,
        state.bpm,
        state.setBpm,
        state.sections,
        state.setSections,
        state.instrumentIDs,
      ],
      []
    ),
    shallow
  );

  // play / pause
  useEffect(() => {
    if (paused) Tone.Transport.pause();
    else Tone.Transport.start();
  }, [paused]);

  // bpm
  useEffect(() => {
    Tone.Transport.bpm.rampTo(bpm, 0.2); // seconds
  }, [bpm]);

  // context startup and setup
  useEffect(() => {
    // Tone.setContext(new Tone.Context({ latencyHint : "playback" })); // improve performance...

    const onclick = () => {
      Tone.start();
      Tone.context.resume();
    };
    window.addEventListener("click", onclick);
    return function cleanup() {
      window.removeEventListener("click", onclick);
    };
  }, []);

  // init synths
  const number_of_tracks = useMemo(
    () => sections.reduce((s, v) => Math.max(s, v.ratios.length), -1),
    [sections]
  );
  useEffect(() => {
    return initSynths(instrumentIDs, number_of_tracks);
  }, [instrumentIDs, number_of_tracks]);

  // sections to actual sound
  useEffect(() => {
    const scheduleSections = require("../lib/scheduleSections").default;

    scheduleSections((time, { accent, duration, track }) => {
      const F = getInstruments()[track];
      try {
        F(duration, time, accent);
      } catch (err) {
        // console.warn(err);
      }
    }, sections);

    return function cleanup() {
      Tone.Transport.cancel(0);
    };
  }, [sections]);

  // dynamic favicon
  useEffect(()=>{
      favicon(sectionsToImgURL(sections));
  }, [sections]);

  // load state from query
  const router = useRouter();
  useEffect(()=>{
      if(Object.keys(router.query).length <= 0) return;
      console.log('found state in url, proceeding to load...');

      setSections(queryToSections(router.query));
      setBpm(Number(router.query.bpm));

      // remove query params
      window.history.replaceState({}, document.title, window.location.pathname);
  }, [router.query]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Polyrhythm Metronome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h2>Polyrhythm Metronome</h2> */}

      <Main></Main>
    </div>
  );
}
