import Head from 'next/head'
// import Image from 'next/image'
import { useTheme } from '../hooks/useTheme'

import Main from '../components/main'

export default function Home() {
  const styles = useTheme(require('../styles/Home.module.sass'));
  return (
    <div 
      className={styles.container}>
      <Head>
        <title>Polyrhythm Metronome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h2>Polyrhythm Metronome</h2> */}

      <Main></Main>

    </div>
  )
}
